services:
  postgres:
    image: postgres:16
    container_name: filecraft-postgres
    environment:
      POSTGRES_DB: filecraft
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "5319764"
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    build: .
    container_name: filecraft-app
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/filecraft
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: "5319764"
      FILECRAFT_STORAGE_ROOT: /file-storage
      FILECRAFT_JWT_SECRET: dev-secret-change-this-dev-secret-change-this
      FILECRAFT_JWT_EXPIRATION_MS: 86400000
    volumes:
      - file-storage:/file-storage

volumes:
  postgres-data:
  file-storage: