spring.application.name=filecraft-backend
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/filecraft}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:5319764}
filecraft.storage.root=${FILECRAFT_STORAGE_ROOT:C:/filecraft-storage}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect