server:
  port: 8080

spring:
  profiles:
    active: local

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/filecraft_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

filecraft:
  storage:
    root: ${FILECRAFT_STORAGE_ROOT:C:/filecraft-storage}