spring.application.name=filecraft-backend
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/filecraft_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:5319764}
filecraft.storage.root=${FILECRAFT_STORAGE_ROOT:C:/filecraft-storage}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
filecraft.jwt.secret=${FILECRAFT_JWT_SECRET:dev-secret-change-this-dev-secret-change-this}
filecraft.jwt.expiration-ms=${FILECRAFT_JWT_EXPIRATION_MS:86400000}